/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "core.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Connect, Connect, AUTO)


PB_BIND(Disconnect, Disconnect, AUTO)


PB_BIND(UpdateSetting, UpdateSetting, AUTO)





