/**
 * @file rover.c
 *
 * @brief This source file was generated by cantools version 40.2.1 Sun Apr 27 20:12:35 2025.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "rover.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t unpack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) << shift);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint32_t unpack_left_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

static inline uint32_t unpack_right_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

int rover_rover_heartbeat_pack(
    uint8_t *dst_p,
    const struct rover_rover_heartbeat_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->rover_status, 0u, 0x0fu);

    return (1);
}

int rover_rover_heartbeat_unpack(
    struct rover_rover_heartbeat_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->rover_status = unpack_right_shift_u8(src_p[0], 0u, 0x0fu);

    return (0);
}

int rover_rover_heartbeat_init(struct rover_rover_heartbeat_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct rover_rover_heartbeat_t));

    return 0;
}

uint8_t rover_rover_heartbeat_rover_status_encode(float value)
{
    return (uint8_t)(value);
}

float rover_rover_heartbeat_rover_status_decode(uint8_t value)
{
    return ((float)value);
}

bool rover_rover_heartbeat_rover_status_is_in_range(uint8_t value)
{
    return (value <= 5u);
}

int rover_device_broadcast_pack(
    uint8_t *dst_p,
    const struct rover_device_broadcast_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_left_shift_u8(src_p->device_value, 0u, 0x1fu);
    dst_p[0] |= pack_left_shift_u8(src_p->fw_version_major, 5u, 0xe0u);
    dst_p[1] |= pack_right_shift_u8(src_p->fw_version_major, 3u, 0x01u);
    dst_p[1] |= pack_left_shift_u8(src_p->fw_version_minor, 1u, 0x1eu);

    return (2);
}

int rover_device_broadcast_unpack(
    struct rover_device_broadcast_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->device_value = unpack_right_shift_u8(src_p[0], 0u, 0x1fu);
    dst_p->fw_version_major = unpack_right_shift_u8(src_p[0], 5u, 0xe0u);
    dst_p->fw_version_major |= unpack_left_shift_u8(src_p[1], 3u, 0x01u);
    dst_p->fw_version_minor = unpack_right_shift_u8(src_p[1], 1u, 0x1eu);

    return (0);
}

int rover_device_broadcast_init(struct rover_device_broadcast_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct rover_device_broadcast_t));

    return 0;
}

uint8_t rover_device_broadcast_device_value_encode(float value)
{
    return (uint8_t)(value);
}

float rover_device_broadcast_device_value_decode(uint8_t value)
{
    return ((float)value);
}

bool rover_device_broadcast_device_value_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t rover_device_broadcast_fw_version_major_encode(float value)
{
    return (uint8_t)(value);
}

float rover_device_broadcast_fw_version_major_decode(uint8_t value)
{
    return ((float)value);
}

bool rover_device_broadcast_fw_version_major_is_in_range(uint8_t value)
{
    return (value <= 8u);
}

uint8_t rover_device_broadcast_fw_version_minor_encode(float value)
{
    return (uint8_t)(value);
}

float rover_device_broadcast_fw_version_minor_decode(uint8_t value)
{
    return ((float)value);
}

bool rover_device_broadcast_fw_version_minor_is_in_range(uint8_t value)
{
    return (value <= 8u);
}

int rover_drive_set_speeds_pack(
    uint8_t *dst_p,
    const struct rover_drive_set_speeds_t *src_p,
    size_t size)
{
    uint16_t left_speed;
    uint16_t right_speed;

    if (size < 7u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 7);

    dst_p[0] |= pack_left_shift_u8(src_p->should_set_left, 0u, 0x01u);
    dst_p[0] |= pack_left_shift_u8(src_p->should_set_right, 1u, 0x02u);
    dst_p[0] |= pack_left_shift_u8(src_p->should_set_throttle, 2u, 0x04u);
    left_speed = (uint16_t)src_p->left_speed;
    dst_p[0] |= pack_left_shift_u16(left_speed, 3u, 0xf8u);
    dst_p[1] |= pack_right_shift_u16(left_speed, 5u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(left_speed, 13u, 0x07u);
    right_speed = (uint16_t)src_p->right_speed;
    dst_p[2] |= pack_left_shift_u16(right_speed, 3u, 0xf8u);
    dst_p[3] |= pack_right_shift_u16(right_speed, 5u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(right_speed, 13u, 0x07u);
    dst_p[4] |= pack_left_shift_u16(src_p->throttle, 3u, 0xf8u);
    dst_p[5] |= pack_right_shift_u16(src_p->throttle, 5u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->throttle, 13u, 0x07u);

    return (7);
}

int rover_drive_set_speeds_unpack(
    struct rover_drive_set_speeds_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t left_speed;
    uint16_t right_speed;

    if (size < 7u) {
        return (-EINVAL);
    }

    dst_p->should_set_left = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->should_set_right = unpack_right_shift_u8(src_p[0], 1u, 0x02u);
    dst_p->should_set_throttle = unpack_right_shift_u8(src_p[0], 2u, 0x04u);
    left_speed = unpack_right_shift_u16(src_p[0], 3u, 0xf8u);
    left_speed |= unpack_left_shift_u16(src_p[1], 5u, 0xffu);
    left_speed |= unpack_left_shift_u16(src_p[2], 13u, 0x07u);
    dst_p->left_speed = (int16_t)left_speed;
    right_speed = unpack_right_shift_u16(src_p[2], 3u, 0xf8u);
    right_speed |= unpack_left_shift_u16(src_p[3], 5u, 0xffu);
    right_speed |= unpack_left_shift_u16(src_p[4], 13u, 0x07u);
    dst_p->right_speed = (int16_t)right_speed;
    dst_p->throttle = unpack_right_shift_u16(src_p[4], 3u, 0xf8u);
    dst_p->throttle |= unpack_left_shift_u16(src_p[5], 5u, 0xffu);
    dst_p->throttle |= unpack_left_shift_u16(src_p[6], 13u, 0x07u);

    return (0);
}

int rover_drive_set_speeds_init(struct rover_drive_set_speeds_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct rover_drive_set_speeds_t));

    return 0;
}

uint8_t rover_drive_set_speeds_should_set_left_encode(float value)
{
    return (uint8_t)(value);
}

float rover_drive_set_speeds_should_set_left_decode(uint8_t value)
{
    return ((float)value);
}

bool rover_drive_set_speeds_should_set_left_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t rover_drive_set_speeds_should_set_right_encode(float value)
{
    return (uint8_t)(value);
}

float rover_drive_set_speeds_should_set_right_decode(uint8_t value)
{
    return ((float)value);
}

bool rover_drive_set_speeds_should_set_right_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t rover_drive_set_speeds_should_set_throttle_encode(float value)
{
    return (uint8_t)(value);
}

float rover_drive_set_speeds_should_set_throttle_decode(uint8_t value)
{
    return ((float)value);
}

bool rover_drive_set_speeds_should_set_throttle_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int16_t rover_drive_set_speeds_left_speed_encode(float value)
{
    return (int16_t)(value / 6.2e-05f);
}

float rover_drive_set_speeds_left_speed_decode(int16_t value)
{
    return ((float)value * 6.2e-05f);
}

bool rover_drive_set_speeds_left_speed_is_in_range(int16_t value)
{
    return ((value >= -16129) && (value <= 16129));
}

int16_t rover_drive_set_speeds_right_speed_encode(float value)
{
    return (int16_t)(value / 6.2e-05f);
}

float rover_drive_set_speeds_right_speed_decode(int16_t value)
{
    return ((float)value * 6.2e-05f);
}

bool rover_drive_set_speeds_right_speed_is_in_range(int16_t value)
{
    return ((value >= -16129) && (value <= 16129));
}

uint16_t rover_drive_set_speeds_throttle_encode(float value)
{
    return (uint16_t)(value / 1.6e-05f);
}

float rover_drive_set_speeds_throttle_decode(uint16_t value)
{
    return ((float)value * 1.6e-05f);
}

bool rover_drive_set_speeds_throttle_is_in_range(uint16_t value)
{
    return (value <= 62500u);
}

int rover_drive_set_led_pack(
    uint8_t *dst_p,
    const struct rover_drive_set_led_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->color, 0u, 0x0fu);
    dst_p[0] |= pack_left_shift_u8(src_p->blink, 4u, 0x10u);

    return (1);
}

int rover_drive_set_led_unpack(
    struct rover_drive_set_led_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->color = unpack_right_shift_u8(src_p[0], 0u, 0x0fu);
    dst_p->blink = unpack_right_shift_u8(src_p[0], 4u, 0x10u);

    return (0);
}

int rover_drive_set_led_init(struct rover_drive_set_led_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct rover_drive_set_led_t));

    return 0;
}

uint8_t rover_drive_set_led_color_encode(float value)
{
    return (uint8_t)(value);
}

float rover_drive_set_led_color_decode(uint8_t value)
{
    return ((float)value);
}

bool rover_drive_set_led_color_is_in_range(uint8_t value)
{
    return (value <= 8u);
}

uint8_t rover_drive_set_led_blink_encode(float value)
{
    return (uint8_t)(value);
}

float rover_drive_set_led_blink_decode(uint8_t value)
{
    return ((float)value);
}

bool rover_drive_set_led_blink_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int rover_drive_led_pack(
    uint8_t *dst_p,
    const struct rover_drive_led_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->color, 0u, 0x0fu);
    dst_p[0] |= pack_left_shift_u8(src_p->blink, 4u, 0x10u);

    return (1);
}

int rover_drive_led_unpack(
    struct rover_drive_led_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->color = unpack_right_shift_u8(src_p[0], 0u, 0x0fu);
    dst_p->blink = unpack_right_shift_u8(src_p[0], 4u, 0x10u);

    return (0);
}

int rover_drive_led_init(struct rover_drive_led_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct rover_drive_led_t));

    return 0;
}

uint8_t rover_drive_led_color_encode(float value)
{
    return (uint8_t)(value);
}

float rover_drive_led_color_decode(uint8_t value)
{
    return ((float)value);
}

bool rover_drive_led_color_is_in_range(uint8_t value)
{
    return (value <= 8u);
}

uint8_t rover_drive_led_blink_encode(float value)
{
    return (uint8_t)(value);
}

float rover_drive_led_blink_decode(uint8_t value)
{
    return ((float)value);
}

bool rover_drive_led_blink_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int rover_drive_applied_output_pack(
    uint8_t *dst_p,
    const struct rover_drive_applied_output_t *src_p,
    size_t size)
{
    uint16_t left_speed;
    uint16_t right_speed;

    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    dst_p[0] |= pack_left_shift_u16(src_p->throttle, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->throttle, 8u, 0xffu);
    left_speed = (uint16_t)src_p->left_speed;
    dst_p[2] |= pack_left_shift_u16(left_speed, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(left_speed, 8u, 0xffu);
    right_speed = (uint16_t)src_p->right_speed;
    dst_p[4] |= pack_left_shift_u16(right_speed, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(right_speed, 8u, 0xffu);

    return (6);
}

int rover_drive_applied_output_unpack(
    struct rover_drive_applied_output_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t left_speed;
    uint16_t right_speed;

    if (size < 6u) {
        return (-EINVAL);
    }

    dst_p->throttle = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->throttle |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    left_speed = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    left_speed |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->left_speed = (int16_t)left_speed;
    right_speed = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    right_speed |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->right_speed = (int16_t)right_speed;

    return (0);
}

int rover_drive_applied_output_init(struct rover_drive_applied_output_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct rover_drive_applied_output_t));

    return 0;
}

uint16_t rover_drive_applied_output_throttle_encode(float value)
{
    return (uint16_t)(value / 1.6e-05f);
}

float rover_drive_applied_output_throttle_decode(uint16_t value)
{
    return ((float)value * 1.6e-05f);
}

bool rover_drive_applied_output_throttle_is_in_range(uint16_t value)
{
    return (value <= 62500u);
}

int16_t rover_drive_applied_output_left_speed_encode(float value)
{
    return (int16_t)(value / 6.2e-05f);
}

float rover_drive_applied_output_left_speed_decode(int16_t value)
{
    return ((float)value * 6.2e-05f);
}

bool rover_drive_applied_output_left_speed_is_in_range(int16_t value)
{
    return ((value >= -16129) && (value <= 16129));
}

int16_t rover_drive_applied_output_right_speed_encode(float value)
{
    return (int16_t)(value / 6.2e-05f);
}

float rover_drive_applied_output_right_speed_decode(int16_t value)
{
    return ((float)value * 6.2e-05f);
}

bool rover_drive_applied_output_right_speed_is_in_range(int16_t value)
{
    return ((value >= -16129) && (value <= 16129));
}

int rover_drive_battery_pack(
    uint8_t *dst_p,
    const struct rover_drive_battery_t *src_p,
    size_t size)
{
    uint16_t temperature;

    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    dst_p[0] |= pack_left_shift_u16(src_p->voltage, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->voltage, 8u, 0xffu);
    temperature = (uint16_t)src_p->temperature;
    dst_p[2] |= pack_left_shift_u16(temperature, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(temperature, 8u, 0x0fu);
    dst_p[3] |= pack_left_shift_u16(src_p->current, 4u, 0xf0u);
    dst_p[4] |= pack_right_shift_u16(src_p->current, 4u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->current, 12u, 0x0fu);

    return (6);
}

int rover_drive_battery_unpack(
    struct rover_drive_battery_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t temperature;

    if (size < 6u) {
        return (-EINVAL);
    }

    dst_p->voltage = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->voltage |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    temperature = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    temperature |= unpack_left_shift_u16(src_p[3], 8u, 0x0fu);

    if ((temperature & (1u << 11)) != 0u) {
        temperature |= 0xf000u;
    }

    dst_p->temperature = (int16_t)temperature;
    dst_p->current = unpack_right_shift_u16(src_p[3], 4u, 0xf0u);
    dst_p->current |= unpack_left_shift_u16(src_p[4], 4u, 0xffu);
    dst_p->current |= unpack_left_shift_u16(src_p[5], 12u, 0x0fu);

    return (0);
}

int rover_drive_battery_init(struct rover_drive_battery_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct rover_drive_battery_t));

    return 0;
}

uint16_t rover_drive_battery_voltage_encode(float value)
{
    return (uint16_t)(value / 0.00055f);
}

float rover_drive_battery_voltage_decode(uint16_t value)
{
    return ((float)value * 0.00055f);
}

bool rover_drive_battery_voltage_is_in_range(uint16_t value)
{
    return (value <= 65455u);
}

int16_t rover_drive_battery_temperature_encode(float value)
{
    return (int16_t)((value - 50.0f) / 0.09f);
}

float rover_drive_battery_temperature_decode(int16_t value)
{
    return (((float)value * 0.09f) + 50.0f);
}

bool rover_drive_battery_temperature_is_in_range(int16_t value)
{
    return ((value >= -1000) && (value <= 1111));
}

uint16_t rover_drive_battery_current_encode(float value)
{
    return (uint16_t)(value / 0.1f);
}

float rover_drive_battery_current_decode(uint16_t value)
{
    return ((float)value * 0.1f);
}

bool rover_drive_battery_current_is_in_range(uint16_t value)
{
    return (value <= 300u);
}

int rover_drive_swivel_pack(
    uint8_t *dst_p,
    const struct rover_drive_swivel_t *src_p,
    size_t size)
{
    uint16_t front_swivel;
    uint16_t front_tilt;
    uint16_t rear_swivel;
    uint16_t rear_tilt;

    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    front_swivel = (uint16_t)src_p->front_swivel;
    dst_p[0] |= pack_left_shift_u16(front_swivel, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(front_swivel, 8u, 0x0fu);
    front_tilt = (uint16_t)src_p->front_tilt;
    dst_p[1] |= pack_left_shift_u16(front_tilt, 4u, 0xf0u);
    dst_p[2] |= pack_right_shift_u16(front_tilt, 4u, 0xffu);
    rear_swivel = (uint16_t)src_p->rear_swivel;
    dst_p[3] |= pack_left_shift_u16(rear_swivel, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(rear_swivel, 8u, 0x0fu);
    rear_tilt = (uint16_t)src_p->rear_tilt;
    dst_p[4] |= pack_left_shift_u16(rear_tilt, 4u, 0xf0u);
    dst_p[5] |= pack_right_shift_u16(rear_tilt, 4u, 0xffu);

    return (6);
}

int rover_drive_swivel_unpack(
    struct rover_drive_swivel_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t front_swivel;
    uint16_t front_tilt;
    uint16_t rear_swivel;
    uint16_t rear_tilt;

    if (size < 6u) {
        return (-EINVAL);
    }

    front_swivel = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    front_swivel |= unpack_left_shift_u16(src_p[1], 8u, 0x0fu);

    if ((front_swivel & (1u << 11)) != 0u) {
        front_swivel |= 0xf000u;
    }

    dst_p->front_swivel = (int16_t)front_swivel;
    front_tilt = unpack_right_shift_u16(src_p[1], 4u, 0xf0u);
    front_tilt |= unpack_left_shift_u16(src_p[2], 4u, 0xffu);

    if ((front_tilt & (1u << 11)) != 0u) {
        front_tilt |= 0xf000u;
    }

    dst_p->front_tilt = (int16_t)front_tilt;
    rear_swivel = unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    rear_swivel |= unpack_left_shift_u16(src_p[4], 8u, 0x0fu);

    if ((rear_swivel & (1u << 11)) != 0u) {
        rear_swivel |= 0xf000u;
    }

    dst_p->rear_swivel = (int16_t)rear_swivel;
    rear_tilt = unpack_right_shift_u16(src_p[4], 4u, 0xf0u);
    rear_tilt |= unpack_left_shift_u16(src_p[5], 4u, 0xffu);

    if ((rear_tilt & (1u << 11)) != 0u) {
        rear_tilt |= 0xf000u;
    }

    dst_p->rear_tilt = (int16_t)rear_tilt;

    return (0);
}

int rover_drive_swivel_init(struct rover_drive_swivel_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct rover_drive_swivel_t));

    return 0;
}

int16_t rover_drive_swivel_front_swivel_encode(float value)
{
    return (int16_t)(value / 0.044f);
}

float rover_drive_swivel_front_swivel_decode(int16_t value)
{
    return ((float)value * 0.044f);
}

bool rover_drive_swivel_front_swivel_is_in_range(int16_t value)
{
    return ((value >= -2045) && (value <= 2045));
}

int16_t rover_drive_swivel_front_tilt_encode(float value)
{
    return (int16_t)(value / 0.044f);
}

float rover_drive_swivel_front_tilt_decode(int16_t value)
{
    return ((float)value * 0.044f);
}

bool rover_drive_swivel_front_tilt_is_in_range(int16_t value)
{
    return ((value >= -2045) && (value <= 2045));
}

int16_t rover_drive_swivel_rear_swivel_encode(float value)
{
    return (int16_t)(value / 0.044f);
}

float rover_drive_swivel_rear_swivel_decode(int16_t value)
{
    return ((float)value * 0.044f);
}

bool rover_drive_swivel_rear_swivel_is_in_range(int16_t value)
{
    return ((value >= -2045) && (value <= 2045));
}

int16_t rover_drive_swivel_rear_tilt_encode(float value)
{
    return (int16_t)(value / 0.044f);
}

float rover_drive_swivel_rear_tilt_decode(int16_t value)
{
    return ((float)value * 0.044f);
}

bool rover_drive_swivel_rear_tilt_is_in_range(int16_t value)
{
    return ((value >= -2045) && (value <= 2045));
}

int rover_relay_set_state_pack(
    uint8_t *dst_p,
    const struct rover_relay_set_state_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_left_shift_u8(src_p->update_front_left_motor, 0u, 0x01u);
    dst_p[0] |= pack_left_shift_u8(src_p->front_left_motor, 1u, 0x02u);
    dst_p[0] |= pack_left_shift_u8(src_p->update_front_right_motor, 2u, 0x04u);
    dst_p[0] |= pack_left_shift_u8(src_p->front_right_motor, 3u, 0x08u);
    dst_p[0] |= pack_left_shift_u8(src_p->update_back_left_motor, 4u, 0x10u);
    dst_p[0] |= pack_left_shift_u8(src_p->back_left_motor, 5u, 0x20u);
    dst_p[0] |= pack_left_shift_u8(src_p->update_back_right_motor, 6u, 0x40u);
    dst_p[0] |= pack_left_shift_u8(src_p->back_right_motor, 7u, 0x80u);
    dst_p[1] |= pack_left_shift_u8(src_p->update_arm, 0u, 0x01u);
    dst_p[1] |= pack_left_shift_u8(src_p->arm, 1u, 0x02u);
    dst_p[1] |= pack_left_shift_u8(src_p->update_science, 2u, 0x04u);
    dst_p[1] |= pack_left_shift_u8(src_p->science, 3u, 0x08u);
    dst_p[1] |= pack_left_shift_u8(src_p->update_drive, 4u, 0x10u);
    dst_p[1] |= pack_left_shift_u8(src_p->drive, 5u, 0x20u);

    return (2);
}

int rover_relay_set_state_unpack(
    struct rover_relay_set_state_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->update_front_left_motor = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->front_left_motor = unpack_right_shift_u8(src_p[0], 1u, 0x02u);
    dst_p->update_front_right_motor = unpack_right_shift_u8(src_p[0], 2u, 0x04u);
    dst_p->front_right_motor = unpack_right_shift_u8(src_p[0], 3u, 0x08u);
    dst_p->update_back_left_motor = unpack_right_shift_u8(src_p[0], 4u, 0x10u);
    dst_p->back_left_motor = unpack_right_shift_u8(src_p[0], 5u, 0x20u);
    dst_p->update_back_right_motor = unpack_right_shift_u8(src_p[0], 6u, 0x40u);
    dst_p->back_right_motor = unpack_right_shift_u8(src_p[0], 7u, 0x80u);
    dst_p->update_arm = unpack_right_shift_u8(src_p[1], 0u, 0x01u);
    dst_p->arm = unpack_right_shift_u8(src_p[1], 1u, 0x02u);
    dst_p->update_science = unpack_right_shift_u8(src_p[1], 2u, 0x04u);
    dst_p->science = unpack_right_shift_u8(src_p[1], 3u, 0x08u);
    dst_p->update_drive = unpack_right_shift_u8(src_p[1], 4u, 0x10u);
    dst_p->drive = unpack_right_shift_u8(src_p[1], 5u, 0x20u);

    return (0);
}

int rover_relay_set_state_init(struct rover_relay_set_state_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct rover_relay_set_state_t));

    return 0;
}

uint8_t rover_relay_set_state_update_front_left_motor_encode(float value)
{
    return (uint8_t)(value);
}

float rover_relay_set_state_update_front_left_motor_decode(uint8_t value)
{
    return ((float)value);
}

bool rover_relay_set_state_update_front_left_motor_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t rover_relay_set_state_front_left_motor_encode(float value)
{
    return (uint8_t)(value);
}

float rover_relay_set_state_front_left_motor_decode(uint8_t value)
{
    return ((float)value);
}

bool rover_relay_set_state_front_left_motor_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t rover_relay_set_state_update_front_right_motor_encode(float value)
{
    return (uint8_t)(value);
}

float rover_relay_set_state_update_front_right_motor_decode(uint8_t value)
{
    return ((float)value);
}

bool rover_relay_set_state_update_front_right_motor_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t rover_relay_set_state_front_right_motor_encode(float value)
{
    return (uint8_t)(value);
}

float rover_relay_set_state_front_right_motor_decode(uint8_t value)
{
    return ((float)value);
}

bool rover_relay_set_state_front_right_motor_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t rover_relay_set_state_update_back_left_motor_encode(float value)
{
    return (uint8_t)(value);
}

float rover_relay_set_state_update_back_left_motor_decode(uint8_t value)
{
    return ((float)value);
}

bool rover_relay_set_state_update_back_left_motor_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t rover_relay_set_state_back_left_motor_encode(float value)
{
    return (uint8_t)(value);
}

float rover_relay_set_state_back_left_motor_decode(uint8_t value)
{
    return ((float)value);
}

bool rover_relay_set_state_back_left_motor_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t rover_relay_set_state_update_back_right_motor_encode(float value)
{
    return (uint8_t)(value);
}

float rover_relay_set_state_update_back_right_motor_decode(uint8_t value)
{
    return ((float)value);
}

bool rover_relay_set_state_update_back_right_motor_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t rover_relay_set_state_back_right_motor_encode(float value)
{
    return (uint8_t)(value);
}

float rover_relay_set_state_back_right_motor_decode(uint8_t value)
{
    return ((float)value);
}

bool rover_relay_set_state_back_right_motor_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t rover_relay_set_state_update_arm_encode(float value)
{
    return (uint8_t)(value);
}

float rover_relay_set_state_update_arm_decode(uint8_t value)
{
    return ((float)value);
}

bool rover_relay_set_state_update_arm_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t rover_relay_set_state_arm_encode(float value)
{
    return (uint8_t)(value);
}

float rover_relay_set_state_arm_decode(uint8_t value)
{
    return ((float)value);
}

bool rover_relay_set_state_arm_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t rover_relay_set_state_update_science_encode(float value)
{
    return (uint8_t)(value);
}

float rover_relay_set_state_update_science_decode(uint8_t value)
{
    return ((float)value);
}

bool rover_relay_set_state_update_science_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t rover_relay_set_state_science_encode(float value)
{
    return (uint8_t)(value);
}

float rover_relay_set_state_science_decode(uint8_t value)
{
    return ((float)value);
}

bool rover_relay_set_state_science_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t rover_relay_set_state_update_drive_encode(float value)
{
    return (uint8_t)(value);
}

float rover_relay_set_state_update_drive_decode(uint8_t value)
{
    return ((float)value);
}

bool rover_relay_set_state_update_drive_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t rover_relay_set_state_drive_encode(float value)
{
    return (uint8_t)(value);
}

float rover_relay_set_state_drive_decode(uint8_t value)
{
    return ((float)value);
}

bool rover_relay_set_state_drive_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int rover_relay_state_pack(
    uint8_t *dst_p,
    const struct rover_relay_state_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->front_left_motor, 0u, 0x01u);
    dst_p[0] |= pack_left_shift_u8(src_p->front_right_motor, 1u, 0x02u);
    dst_p[0] |= pack_left_shift_u8(src_p->back_left_motor, 2u, 0x04u);
    dst_p[0] |= pack_left_shift_u8(src_p->back_right_motor, 3u, 0x08u);
    dst_p[0] |= pack_left_shift_u8(src_p->drive, 4u, 0x10u);
    dst_p[0] |= pack_left_shift_u8(src_p->arm, 5u, 0x20u);
    dst_p[0] |= pack_left_shift_u8(src_p->science, 6u, 0x40u);
    dst_p[0] |= pack_left_shift_u8(src_p->physical_override, 7u, 0x80u);

    return (1);
}

int rover_relay_state_unpack(
    struct rover_relay_state_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->front_left_motor = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->front_right_motor = unpack_right_shift_u8(src_p[0], 1u, 0x02u);
    dst_p->back_left_motor = unpack_right_shift_u8(src_p[0], 2u, 0x04u);
    dst_p->back_right_motor = unpack_right_shift_u8(src_p[0], 3u, 0x08u);
    dst_p->drive = unpack_right_shift_u8(src_p[0], 4u, 0x10u);
    dst_p->arm = unpack_right_shift_u8(src_p[0], 5u, 0x20u);
    dst_p->science = unpack_right_shift_u8(src_p[0], 6u, 0x40u);
    dst_p->physical_override = unpack_right_shift_u8(src_p[0], 7u, 0x80u);

    return (0);
}

int rover_relay_state_init(struct rover_relay_state_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct rover_relay_state_t));

    return 0;
}

uint8_t rover_relay_state_front_left_motor_encode(float value)
{
    return (uint8_t)(value);
}

float rover_relay_state_front_left_motor_decode(uint8_t value)
{
    return ((float)value);
}

bool rover_relay_state_front_left_motor_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t rover_relay_state_front_right_motor_encode(float value)
{
    return (uint8_t)(value);
}

float rover_relay_state_front_right_motor_decode(uint8_t value)
{
    return ((float)value);
}

bool rover_relay_state_front_right_motor_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t rover_relay_state_back_left_motor_encode(float value)
{
    return (uint8_t)(value);
}

float rover_relay_state_back_left_motor_decode(uint8_t value)
{
    return ((float)value);
}

bool rover_relay_state_back_left_motor_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t rover_relay_state_back_right_motor_encode(float value)
{
    return (uint8_t)(value);
}

float rover_relay_state_back_right_motor_decode(uint8_t value)
{
    return ((float)value);
}

bool rover_relay_state_back_right_motor_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t rover_relay_state_drive_encode(float value)
{
    return (uint8_t)(value);
}

float rover_relay_state_drive_decode(uint8_t value)
{
    return ((float)value);
}

bool rover_relay_state_drive_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t rover_relay_state_arm_encode(float value)
{
    return (uint8_t)(value);
}

float rover_relay_state_arm_decode(uint8_t value)
{
    return ((float)value);
}

bool rover_relay_state_arm_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t rover_relay_state_science_encode(float value)
{
    return (uint8_t)(value);
}

float rover_relay_state_science_decode(uint8_t value)
{
    return ((float)value);
}

bool rover_relay_state_science_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t rover_relay_state_physical_override_encode(float value)
{
    return (uint8_t)(value);
}

float rover_relay_state_physical_override_decode(uint8_t value)
{
    return ((float)value);
}

bool rover_relay_state_physical_override_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int rover_drive_set_swivel_pack(
    uint8_t *dst_p,
    const struct rover_drive_set_swivel_t *src_p,
    size_t size)
{
    uint16_t front_swivel;
    uint16_t front_tilt;
    uint16_t rear_swivel;
    uint16_t rear_tilt;

    if (size < 7u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 7);

    dst_p[0] |= pack_left_shift_u8(src_p->set_front_swivel, 0u, 0x01u);
    dst_p[0] |= pack_left_shift_u8(src_p->set_front_tilt, 1u, 0x02u);
    dst_p[0] |= pack_left_shift_u8(src_p->set_rear_swivel, 2u, 0x04u);
    dst_p[0] |= pack_left_shift_u8(src_p->set_rear_tilt, 3u, 0x08u);
    front_swivel = (uint16_t)src_p->front_swivel;
    dst_p[0] |= pack_left_shift_u16(front_swivel, 4u, 0xf0u);
    dst_p[1] |= pack_right_shift_u16(front_swivel, 4u, 0xffu);
    front_tilt = (uint16_t)src_p->front_tilt;
    dst_p[2] |= pack_left_shift_u16(front_tilt, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(front_tilt, 8u, 0x0fu);
    rear_swivel = (uint16_t)src_p->rear_swivel;
    dst_p[3] |= pack_left_shift_u16(rear_swivel, 4u, 0xf0u);
    dst_p[4] |= pack_right_shift_u16(rear_swivel, 4u, 0xffu);
    rear_tilt = (uint16_t)src_p->rear_tilt;
    dst_p[5] |= pack_left_shift_u16(rear_tilt, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(rear_tilt, 8u, 0x0fu);

    return (7);
}

int rover_drive_set_swivel_unpack(
    struct rover_drive_set_swivel_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t front_swivel;
    uint16_t front_tilt;
    uint16_t rear_swivel;
    uint16_t rear_tilt;

    if (size < 7u) {
        return (-EINVAL);
    }

    dst_p->set_front_swivel = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->set_front_tilt = unpack_right_shift_u8(src_p[0], 1u, 0x02u);
    dst_p->set_rear_swivel = unpack_right_shift_u8(src_p[0], 2u, 0x04u);
    dst_p->set_rear_tilt = unpack_right_shift_u8(src_p[0], 3u, 0x08u);
    front_swivel = unpack_right_shift_u16(src_p[0], 4u, 0xf0u);
    front_swivel |= unpack_left_shift_u16(src_p[1], 4u, 0xffu);

    if ((front_swivel & (1u << 11)) != 0u) {
        front_swivel |= 0xf000u;
    }

    dst_p->front_swivel = (int16_t)front_swivel;
    front_tilt = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    front_tilt |= unpack_left_shift_u16(src_p[3], 8u, 0x0fu);

    if ((front_tilt & (1u << 11)) != 0u) {
        front_tilt |= 0xf000u;
    }

    dst_p->front_tilt = (int16_t)front_tilt;
    rear_swivel = unpack_right_shift_u16(src_p[3], 4u, 0xf0u);
    rear_swivel |= unpack_left_shift_u16(src_p[4], 4u, 0xffu);

    if ((rear_swivel & (1u << 11)) != 0u) {
        rear_swivel |= 0xf000u;
    }

    dst_p->rear_swivel = (int16_t)rear_swivel;
    rear_tilt = unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    rear_tilt |= unpack_left_shift_u16(src_p[6], 8u, 0x0fu);

    if ((rear_tilt & (1u << 11)) != 0u) {
        rear_tilt |= 0xf000u;
    }

    dst_p->rear_tilt = (int16_t)rear_tilt;

    return (0);
}

int rover_drive_set_swivel_init(struct rover_drive_set_swivel_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct rover_drive_set_swivel_t));

    return 0;
}

uint8_t rover_drive_set_swivel_set_front_swivel_encode(float value)
{
    return (uint8_t)(value);
}

float rover_drive_set_swivel_set_front_swivel_decode(uint8_t value)
{
    return ((float)value);
}

bool rover_drive_set_swivel_set_front_swivel_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t rover_drive_set_swivel_set_front_tilt_encode(float value)
{
    return (uint8_t)(value);
}

float rover_drive_set_swivel_set_front_tilt_decode(uint8_t value)
{
    return ((float)value);
}

bool rover_drive_set_swivel_set_front_tilt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t rover_drive_set_swivel_set_rear_swivel_encode(float value)
{
    return (uint8_t)(value);
}

float rover_drive_set_swivel_set_rear_swivel_decode(uint8_t value)
{
    return ((float)value);
}

bool rover_drive_set_swivel_set_rear_swivel_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t rover_drive_set_swivel_set_rear_tilt_encode(float value)
{
    return (uint8_t)(value);
}

float rover_drive_set_swivel_set_rear_tilt_decode(uint8_t value)
{
    return ((float)value);
}

bool rover_drive_set_swivel_set_rear_tilt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int16_t rover_drive_set_swivel_front_swivel_encode(float value)
{
    return (int16_t)(value / 0.044f);
}

float rover_drive_set_swivel_front_swivel_decode(int16_t value)
{
    return ((float)value * 0.044f);
}

bool rover_drive_set_swivel_front_swivel_is_in_range(int16_t value)
{
    return ((value >= -2045) && (value <= 2045));
}

int16_t rover_drive_set_swivel_front_tilt_encode(float value)
{
    return (int16_t)(value / 0.044f);
}

float rover_drive_set_swivel_front_tilt_decode(int16_t value)
{
    return ((float)value * 0.044f);
}

bool rover_drive_set_swivel_front_tilt_is_in_range(int16_t value)
{
    return ((value >= -2045) && (value <= 2045));
}

int16_t rover_drive_set_swivel_rear_swivel_encode(float value)
{
    return (int16_t)(value / 0.044f);
}

float rover_drive_set_swivel_rear_swivel_decode(int16_t value)
{
    return ((float)value * 0.044f);
}

bool rover_drive_set_swivel_rear_swivel_is_in_range(int16_t value)
{
    return ((value >= -2045) && (value <= 2045));
}

int16_t rover_drive_set_swivel_rear_tilt_encode(float value)
{
    return (int16_t)(value / 0.044f);
}

float rover_drive_set_swivel_rear_tilt_decode(int16_t value)
{
    return ((float)value * 0.044f);
}

bool rover_drive_set_swivel_rear_tilt_is_in_range(int16_t value)
{
    return ((value >= -2045) && (value <= 2045));
}

int rover_arm_set_motor_pack(
    uint8_t *dst_p,
    const struct rover_arm_set_motor_t *src_p,
    size_t size)
{
    uint16_t angle;
    uint16_t move_radians;
    uint32_t move_steps;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->motor_value, 0u, 0x07u);
    move_steps = (uint32_t)src_p->move_steps;
    dst_p[0] |= pack_left_shift_u32(move_steps, 3u, 0xf8u);
    dst_p[1] |= pack_right_shift_u32(move_steps, 5u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(move_steps, 13u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(move_steps, 21u, 0x07u);
    move_radians = (uint16_t)src_p->move_radians;
    dst_p[3] |= pack_left_shift_u16(move_radians, 3u, 0xf8u);
    dst_p[4] |= pack_right_shift_u16(move_radians, 5u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(move_radians, 13u, 0x07u);
    angle = (uint16_t)src_p->angle;
    dst_p[5] |= pack_left_shift_u16(angle, 3u, 0xf8u);
    dst_p[6] |= pack_right_shift_u16(angle, 5u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(angle, 13u, 0x07u);

    return (8);
}

int rover_arm_set_motor_unpack(
    struct rover_arm_set_motor_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t angle;
    uint16_t move_radians;
    uint32_t move_steps;

    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->motor_value = unpack_right_shift_u8(src_p[0], 0u, 0x07u);
    move_steps = unpack_right_shift_u32(src_p[0], 3u, 0xf8u);
    move_steps |= unpack_left_shift_u32(src_p[1], 5u, 0xffu);
    move_steps |= unpack_left_shift_u32(src_p[2], 13u, 0xffu);
    move_steps |= unpack_left_shift_u32(src_p[3], 21u, 0x07u);

    if ((move_steps & (1u << 23)) != 0u) {
        move_steps |= 0xff000000u;
    }

    dst_p->move_steps = (int32_t)move_steps;
    move_radians = unpack_right_shift_u16(src_p[3], 3u, 0xf8u);
    move_radians |= unpack_left_shift_u16(src_p[4], 5u, 0xffu);
    move_radians |= unpack_left_shift_u16(src_p[5], 13u, 0x07u);
    dst_p->move_radians = (int16_t)move_radians;
    angle = unpack_right_shift_u16(src_p[5], 3u, 0xf8u);
    angle |= unpack_left_shift_u16(src_p[6], 5u, 0xffu);
    angle |= unpack_left_shift_u16(src_p[7], 13u, 0x07u);
    dst_p->angle = (int16_t)angle;

    return (0);
}

int rover_arm_set_motor_init(struct rover_arm_set_motor_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct rover_arm_set_motor_t));

    return 0;
}

uint8_t rover_arm_set_motor_motor_value_encode(float value)
{
    return (uint8_t)(value);
}

float rover_arm_set_motor_motor_value_decode(uint8_t value)
{
    return ((float)value);
}

bool rover_arm_set_motor_motor_value_is_in_range(uint8_t value)
{
    return (value <= 8u);
}

int32_t rover_arm_set_motor_move_steps_encode(float value)
{
    return (int32_t)(value);
}

float rover_arm_set_motor_move_steps_decode(int32_t value)
{
    return ((float)value);
}

bool rover_arm_set_motor_move_steps_is_in_range(int32_t value)
{
    return ((value >= -8388608) && (value <= 8388608));
}

int16_t rover_arm_set_motor_move_radians_encode(float value)
{
    return (int16_t)(value / 9.58738e-05f);
}

float rover_arm_set_motor_move_radians_decode(int16_t value)
{
    return ((float)value * 9.58738e-05f);
}

bool rover_arm_set_motor_move_radians_is_in_range(int16_t value)
{
    return (value >= -32767);
}

int16_t rover_arm_set_motor_angle_encode(float value)
{
    return (int16_t)(value / 9.58738e-05f);
}

float rover_arm_set_motor_angle_decode(int16_t value)
{
    return ((float)value * 9.58738e-05f);
}

bool rover_arm_set_motor_angle_is_in_range(int16_t value)
{
    return ((value >= -32767) && (value <= -32767));
}

int rover_arm_motor_move_data_pack(
    uint8_t *dst_p,
    const struct rover_arm_motor_move_data_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_left_shift_u8(src_p->motor_value, 0u, 0x07u);
    dst_p[0] |= pack_left_shift_u8(src_p->is_moving, 3u, 0x18u);
    dst_p[0] |= pack_left_shift_u8(src_p->is_limit_switch_pressed, 5u, 0x60u);
    dst_p[0] |= pack_left_shift_u8(src_p->motor_direction, 7u, 0x80u);
    dst_p[1] |= pack_right_shift_u8(src_p->motor_direction, 1u, 0x07u);

    return (2);
}

int rover_arm_motor_move_data_unpack(
    struct rover_arm_motor_move_data_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->motor_value = unpack_right_shift_u8(src_p[0], 0u, 0x07u);
    dst_p->is_moving = unpack_right_shift_u8(src_p[0], 3u, 0x18u);
    dst_p->is_limit_switch_pressed = unpack_right_shift_u8(src_p[0], 5u, 0x60u);
    dst_p->motor_direction = unpack_right_shift_u8(src_p[0], 7u, 0x80u);
    dst_p->motor_direction |= unpack_left_shift_u8(src_p[1], 1u, 0x07u);

    return (0);
}

int rover_arm_motor_move_data_init(struct rover_arm_motor_move_data_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct rover_arm_motor_move_data_t));

    return 0;
}

uint8_t rover_arm_motor_move_data_motor_value_encode(float value)
{
    return (uint8_t)(value);
}

float rover_arm_motor_move_data_motor_value_decode(uint8_t value)
{
    return ((float)value);
}

bool rover_arm_motor_move_data_motor_value_is_in_range(uint8_t value)
{
    return (value <= 8u);
}

uint8_t rover_arm_motor_move_data_is_moving_encode(float value)
{
    return (uint8_t)(value);
}

float rover_arm_motor_move_data_is_moving_decode(uint8_t value)
{
    return ((float)value);
}

bool rover_arm_motor_move_data_is_moving_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t rover_arm_motor_move_data_is_limit_switch_pressed_encode(float value)
{
    return (uint8_t)(value);
}

float rover_arm_motor_move_data_is_limit_switch_pressed_decode(uint8_t value)
{
    return ((float)value);
}

bool rover_arm_motor_move_data_is_limit_switch_pressed_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t rover_arm_motor_move_data_motor_direction_encode(float value)
{
    return (uint8_t)(value);
}

float rover_arm_motor_move_data_motor_direction_decode(uint8_t value)
{
    return ((float)value);
}

bool rover_arm_motor_move_data_motor_direction_is_in_range(uint8_t value)
{
    return (value <= 9u);
}

int rover_arm_motor_step_data_pack(
    uint8_t *dst_p,
    const struct rover_arm_motor_step_data_t *src_p,
    size_t size)
{
    uint32_t current_step;
    uint32_t target_step;

    if (size < 7u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 7);

    dst_p[0] |= pack_left_shift_u8(src_p->motor_value, 0u, 0x0fu);
    current_step = (uint32_t)src_p->current_step;
    dst_p[0] |= pack_left_shift_u32(current_step, 4u, 0xf0u);
    dst_p[1] |= pack_right_shift_u32(current_step, 4u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(current_step, 12u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(current_step, 20u, 0x0fu);
    target_step = (uint32_t)src_p->target_step;
    dst_p[3] |= pack_left_shift_u32(target_step, 4u, 0xf0u);
    dst_p[4] |= pack_right_shift_u32(target_step, 4u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(target_step, 12u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(target_step, 20u, 0x0fu);

    return (7);
}

int rover_arm_motor_step_data_unpack(
    struct rover_arm_motor_step_data_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t current_step;
    uint32_t target_step;

    if (size < 7u) {
        return (-EINVAL);
    }

    dst_p->motor_value = unpack_right_shift_u8(src_p[0], 0u, 0x0fu);
    current_step = unpack_right_shift_u32(src_p[0], 4u, 0xf0u);
    current_step |= unpack_left_shift_u32(src_p[1], 4u, 0xffu);
    current_step |= unpack_left_shift_u32(src_p[2], 12u, 0xffu);
    current_step |= unpack_left_shift_u32(src_p[3], 20u, 0x0fu);

    if ((current_step & (1u << 23)) != 0u) {
        current_step |= 0xff000000u;
    }

    dst_p->current_step = (int32_t)current_step;
    target_step = unpack_right_shift_u32(src_p[3], 4u, 0xf0u);
    target_step |= unpack_left_shift_u32(src_p[4], 4u, 0xffu);
    target_step |= unpack_left_shift_u32(src_p[5], 12u, 0xffu);
    target_step |= unpack_left_shift_u32(src_p[6], 20u, 0x0fu);

    if ((target_step & (1u << 23)) != 0u) {
        target_step |= 0xff000000u;
    }

    dst_p->target_step = (int32_t)target_step;

    return (0);
}

int rover_arm_motor_step_data_init(struct rover_arm_motor_step_data_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct rover_arm_motor_step_data_t));

    return 0;
}

uint8_t rover_arm_motor_step_data_motor_value_encode(float value)
{
    return (uint8_t)(value);
}

float rover_arm_motor_step_data_motor_value_decode(uint8_t value)
{
    return ((float)value);
}

bool rover_arm_motor_step_data_motor_value_is_in_range(uint8_t value)
{
    return (value <= 8u);
}

int32_t rover_arm_motor_step_data_current_step_encode(float value)
{
    return (int32_t)(value);
}

float rover_arm_motor_step_data_current_step_decode(int32_t value)
{
    return ((float)value);
}

bool rover_arm_motor_step_data_current_step_is_in_range(int32_t value)
{
    return ((value >= -8388608) && (value <= 8388608));
}

int32_t rover_arm_motor_step_data_target_step_encode(float value)
{
    return (int32_t)(value);
}

float rover_arm_motor_step_data_target_step_decode(int32_t value)
{
    return ((float)value);
}

bool rover_arm_motor_step_data_target_step_is_in_range(int32_t value)
{
    return ((value >= -8388608) && (value <= 8388608));
}

int rover_arm_motor_angle_data_pack(
    uint8_t *dst_p,
    const struct rover_arm_motor_angle_data_t *src_p,
    size_t size)
{
    if (size < 5u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 5);

    dst_p[0] |= pack_left_shift_u8(src_p->motor_value, 0u, 0x07u);
    dst_p[0] |= pack_left_shift_u16(src_p->current_angle, 3u, 0xf8u);
    dst_p[1] |= pack_right_shift_u16(src_p->current_angle, 5u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->current_angle, 13u, 0x07u);
    dst_p[2] |= pack_left_shift_u16(src_p->target_angle, 3u, 0xf8u);
    dst_p[3] |= pack_right_shift_u16(src_p->target_angle, 5u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->target_angle, 13u, 0x07u);

    return (5);
}

int rover_arm_motor_angle_data_unpack(
    struct rover_arm_motor_angle_data_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 5u) {
        return (-EINVAL);
    }

    dst_p->motor_value = unpack_right_shift_u8(src_p[0], 0u, 0x07u);
    dst_p->current_angle = unpack_right_shift_u16(src_p[0], 3u, 0xf8u);
    dst_p->current_angle |= unpack_left_shift_u16(src_p[1], 5u, 0xffu);
    dst_p->current_angle |= unpack_left_shift_u16(src_p[2], 13u, 0x07u);
    dst_p->target_angle = unpack_right_shift_u16(src_p[2], 3u, 0xf8u);
    dst_p->target_angle |= unpack_left_shift_u16(src_p[3], 5u, 0xffu);
    dst_p->target_angle |= unpack_left_shift_u16(src_p[4], 13u, 0x07u);

    return (0);
}

int rover_arm_motor_angle_data_init(struct rover_arm_motor_angle_data_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct rover_arm_motor_angle_data_t));

    return 0;
}

uint8_t rover_arm_motor_angle_data_motor_value_encode(float value)
{
    return (uint8_t)(value);
}

float rover_arm_motor_angle_data_motor_value_decode(uint8_t value)
{
    return ((float)value);
}

bool rover_arm_motor_angle_data_motor_value_is_in_range(uint8_t value)
{
    return (value <= 8u);
}

uint16_t rover_arm_motor_angle_data_current_angle_encode(float value)
{
    return (uint16_t)(value / 9.587379e-05f);
}

float rover_arm_motor_angle_data_current_angle_decode(uint16_t value)
{
    return ((float)value * 9.587379e-05f);
}

bool rover_arm_motor_angle_data_current_angle_is_in_range(uint16_t value)
{
    return (value <= 32768u);
}

uint16_t rover_arm_motor_angle_data_target_angle_encode(float value)
{
    return (uint16_t)(value / 9.587379e-05f);
}

float rover_arm_motor_angle_data_target_angle_decode(uint16_t value)
{
    return ((float)value * 9.587379e-05f);
}

bool rover_arm_motor_angle_data_target_angle_is_in_range(uint16_t value)
{
    return (value <= 32768u);
}
