/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_VERSION_PB_H_INCLUDED
#define PB_VERSION_PB_H_INCLUDED
#include "pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _Version {
    int32_t major;
    int32_t minor;
} Version;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Version_init_default                     {0, 0}
#define Version_init_zero                        {0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define Version_major_tag                        1
#define Version_minor_tag                        2

/* Struct field encoding specification for nanopb */
#define Version_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    major,             1) \
X(a, STATIC,   SINGULAR, INT32,    minor,             2)
#define Version_CALLBACK NULL
#define Version_DEFAULT NULL

extern const pb_msgdesc_t Version_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Version_fields &Version_msg

/* Maximum encoded size of messages (where known) */
#define VERSION_PB_H_MAX_SIZE                    Version_size
#define Version_size                             22

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
