/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_WRAPPER_PB_H_INCLUDED
#define PB_WRAPPER_PB_H_INCLUDED
#include "pb.h"
#include "google/protobuf/timestamp.pb.h"
#include "version.pb.h"
#include "core.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _MessageType {
    MessageType_HEARTBEAT = 0,
    MessageType_DISCONNECT = 1,
    MessageType_LOG_MESSAGE = 2,
    MessageType_DATA = 3,
    MessageType_COMMAND = 4
} MessageType;

/* Struct definitions */
typedef struct _WrappedMessage {
    pb_callback_t data;
    pb_callback_t name; /* legacy */
    bool has_timestamp;
    google_protobuf_Timestamp timestamp;
    bool has_version;
    Version version;
    MessageType type;
    Device sender;
    bool needsReceipt;
} WrappedMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _MessageType_MIN MessageType_HEARTBEAT
#define _MessageType_MAX MessageType_COMMAND
#define _MessageType_ARRAYSIZE ((MessageType)(MessageType_COMMAND+1))

#define WrappedMessage_type_ENUMTYPE MessageType
#define WrappedMessage_sender_ENUMTYPE Device


/* Initializer values for message structs */
#define WrappedMessage_init_default              {{{NULL}, NULL}, {{NULL}, NULL}, false, google_protobuf_Timestamp_init_default, false, Version_init_default, _MessageType_MIN, _Device_MIN, 0}
#define WrappedMessage_init_zero                 {{{NULL}, NULL}, {{NULL}, NULL}, false, google_protobuf_Timestamp_init_zero, false, Version_init_zero, _MessageType_MIN, _Device_MIN, 0}

/* Field tags (for use in manual encoding/decoding) */
#define WrappedMessage_data_tag                  1
#define WrappedMessage_name_tag                  2
#define WrappedMessage_timestamp_tag             3
#define WrappedMessage_version_tag               4
#define WrappedMessage_type_tag                  5
#define WrappedMessage_sender_tag                6
#define WrappedMessage_needsReceipt_tag          7

/* Struct field encoding specification for nanopb */
#define WrappedMessage_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    data,              1) \
X(a, CALLBACK, SINGULAR, STRING,   name,              2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  timestamp,         3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  version,           4) \
X(a, STATIC,   SINGULAR, UENUM,    type,              5) \
X(a, STATIC,   SINGULAR, UENUM,    sender,            6) \
X(a, STATIC,   SINGULAR, BOOL,     needsReceipt,      7)
#define WrappedMessage_CALLBACK pb_default_field_callback
#define WrappedMessage_DEFAULT NULL
#define WrappedMessage_timestamp_MSGTYPE google_protobuf_Timestamp
#define WrappedMessage_version_MSGTYPE Version

extern const pb_msgdesc_t WrappedMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define WrappedMessage_fields &WrappedMessage_msg

/* Maximum encoded size of messages (where known) */
/* WrappedMessage_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
